CREATE TABLE "Leads" (
  "LeadID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" string,
  "last_name" string,
  "zip_code" string,
  "phone" int,
  "email" string,
  "address1" string,
  "address2" string,
  "city" string,
  "state" string,
  "zip" string
);

CREATE TABLE "Leads_Metadata" (
  "id" SERIAL PRIMARY KEY,
  "LeadID" int,
  "utm_medium" string,
  "utm_source" string,
  "utm_campaign" string,
  "utm_term" string,
  "utm_content" string,
  "lead_form_survey_answers" json
);

ALTER TABLE "Leads" ADD FOREIGN KEY ("LeadID") REFERENCES "Leads_Metadata" ("LeadID") DEFERRABLE INITIALLY IMMEDIATE;
