-- Migration: initial_schema
-- Creates Leads and Leads_Metadata tables with RLS policies.
-- Source of truth: docs/schema.dbml + SPEC.md Section 5 (Phase 2)

-- ─────────────────────────────────────────────────────────────────────────────
-- Leads
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "Leads" (
  "LeadID"     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" TEXT,
  "last_name"  TEXT,
  "zip_code"   TEXT,
  -- ASSUMPTION: phone stored as TEXT. DBML defines it as int but the form
  -- collects and validates it as a 10-digit string. Casting to int at insert
  -- time would silently discard leading zeros on rare area codes.
  "phone"      TEXT,
  "email"      TEXT,
  "address1"   TEXT,
  "address2"   TEXT,
  "city"       TEXT,
  "state"      TEXT,
  "zip"        TEXT
);

-- ─────────────────────────────────────────────────────────────────────────────
-- Leads_Metadata
-- ─────────────────────────────────────────────────────────────────────────────
-- DBML specifies id as uuid. Using gen_random_uuid() as the default since
-- UUIDs do not auto-increment; SERIAL was listed in the spec SQL pseudocode
-- but uuid is the explicit type in the DBML and is idiomatic for Supabase.
CREATE TABLE IF NOT EXISTS "Leads_Metadata" (
  "id"                       UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  "LeadID"                   INTEGER REFERENCES "Leads" ("LeadID"),
  "utm_medium"               TEXT,
  "utm_source"               TEXT,
  "utm_campaign"             TEXT,
  "utm_term"                 TEXT,
  "utm_content"              TEXT,
  -- Using JSONB (binary JSON) instead of JSON for better indexing and query performance.
  "lead_form_survey_answers" JSONB
);

-- ─────────────────────────────────────────────────────────────────────────────
-- Row Level Security — Leads
-- Allow anonymous inserts only. All other operations are denied by default
-- once RLS is enabled (no matching policy = implicit deny).
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE "Leads" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "anon_insert_leads"
  ON "Leads"
  FOR INSERT
  TO anon
  WITH CHECK (true);

-- ─────────────────────────────────────────────────────────────────────────────
-- Row Level Security — Leads_Metadata
-- Same restriction: anonymous inserts allowed, everything else denied.
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE "Leads_Metadata" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "anon_insert_leads_metadata"
  ON "Leads_Metadata"
  FOR INSERT
  TO anon
  WITH CHECK (true);
